# Numpy Intro

In [48]:
import numpy as np

In [49]:
np.int64(2) ** 1000

0

In [50]:
arr = np.array([1,2,3])

In [51]:
len(arr)

3

In [52]:
arr.dtype

dtype('int32')

In [53]:
arr32 = np.array([1,2,3],dtype=np.int32)
arr32

array([1, 2, 3])

In [54]:
arr32.dtype

dtype('int32')

In [55]:
arr*arr

array([1, 4, 9])

In [56]:
v1 = np.random.rand(100000)
v2 = np.random.rand(100000)

In [57]:
%time v1 * v2

Wall time: 0 ns


array([0.01584716, 0.22649762, 0.6236994 , ..., 0.05877201, 0.02013526,
       0.34832718])

In [58]:
np.dot(arr,arr)

14

In [59]:
mat = np.array(([1,2,3],[4,5,6],[7,8,9]))
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
v =np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
v.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [62]:
mat = np.arange(12).reshape(4,3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [63]:
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

# Slicing

In [64]:
num = [1,2,3,4,5,6]
num[1:2]

[2]

In [65]:
v = np.arange(1,6)
print(v)
print(v[1:3])

[1 2 3 4 5]
[2 3]


In [66]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
arr[1,1]

5

In [68]:
arr[:,2]

array([ 2,  6, 10])

In [69]:
arr[:,2].reshape(3,1)

array([[ 2],
       [ 6],
       [10]])

In [70]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
arr[1:,2:] = 7

In [72]:
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])

#  Boolean Indexing

In [73]:
arr = np.arange(3)

In [74]:
arr

array([0, 1, 2])

In [75]:
arr[np.array([True,False,True])]

array([0, 2])

In [76]:
arr >= 1

array([False,  True,  True])

In [77]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr[(arr>2) & (arr <7)]

array([3, 4, 5, 6])

In [79]:
arr[(arr>2) | (arr <7)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [81]:
mat = np.random.rand(5,5)
mat

array([[0.92545975, 0.35966928, 0.72935887, 0.98732989, 0.6555841 ],
       [0.53083379, 0.5148488 , 0.01111097, 0.00394408, 0.37110585],
       [0.77275732, 0.97789863, 0.69504635, 0.84022794, 0.26009306],
       [0.97384145, 0.65376012, 0.84779508, 0.30527359, 0.48461237],
       [0.55333864, 0.95393551, 0.44627243, 0.35017677, 0.60857831]])

In [82]:
np.abs(mat-mat.mean())

array([[0.33294563, 0.23284484, 0.13684475, 0.39481578, 0.06306998],
       [0.06168033, 0.07766532, 0.58140315, 0.58857004, 0.22140826],
       [0.1802432 , 0.38538452, 0.10253223, 0.24771382, 0.33242106],
       [0.38132734, 0.061246  , 0.25528096, 0.28724053, 0.10790175],
       [0.03917548, 0.36142139, 0.14624169, 0.24233735, 0.01606419]])

In [83]:
np.abs(mat-mat.mean() > 1.5*mat.std())

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [84]:
mat[np.abs(mat-mat.mean() > 1.5*mat.std())] = mat.mean()
mat

array([[0.92545975, 0.35966928, 0.72935887, 0.98732989, 0.6555841 ],
       [0.53083379, 0.5148488 , 0.01111097, 0.00394408, 0.37110585],
       [0.77275732, 0.97789863, 0.69504635, 0.84022794, 0.26009306],
       [0.97384145, 0.65376012, 0.84779508, 0.30527359, 0.48461237],
       [0.55333864, 0.95393551, 0.44627243, 0.35017677, 0.60857831]])

In [85]:
arr = np.arange(3)
arr+4

array([4, 5, 6])

In [86]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [87]:
arr

array([0, 1, 2])

In [88]:
np.sin(np.pi/2)

1.0

In [89]:
v = np.arange(-3,3)
np.sin(v)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743])

In [90]:
def noneg(n):
    if n < 0:
        return 0
    return n

In [91]:
noneg(7)

7

In [92]:
noneg(v)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [93]:
@np.vectorize
def noneg(n):
    if n < 0:
        return 0
    return n

noneg = np.vectorize(noneg)

In [94]:
noneg(v)

array([0, 0, 0, 0, 1, 2])

In [95]:
import pandas as pd
s = pd.Series(np.arange(5))